### ISSUE TITLE
[BUG] :  Not connecting to Steam

### ISSUE THREAD

**Issue by AngusIrwin** [Zagrios/bs-manager#217]
**Describe the bug**
Login with username and password, but getting an error.

**To Reproduce**
1. Download any game version.
2. Put in login details.
3. Buffers for 30 seconds, then warns it can't connect to Steam.
4. Version disappears.

**Expected behaviour**
Game version begins download.

**Logs**
[2023-4-22-v1.1.1.log](https://github.com/Zagrios/bs-manager/files/11300379/2023-4-22-v1.1.1.log)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v1.1.1

**Additional context**
I am using Steam Guard but not getting a popup for it. Logs say connection to Steam failed followed by the error "Timeout connecting to Steam3." See logs for more details.

**Comment by Zagrios** [comment]
Hello,

Thank you for reaching out to us. If you are still experiencing the issue today, I suggest trying the procedure to remove Steam Guard authorizations to see if it resolves your problem:

- Log in to your Steam account via a web browser.
- Go to your account settings page by clicking on your username at the top right corner, and then selecting "Account Details" from the drop-down menu.
- In the "Account Security" section, click on "Manage Steam Guard Authenticator."
- Select "Remove other authorizations" to delete existing authorizations on other devices.
- Once the authorizations have been removed, try download a version of BeatSaber

If the issue persists after following these steps, please don't hesitate to let us know so that we can continue to assist you.

**Comment by AngusIrwin** [comment]
Thanks for the suggestion, unfortunately it didn't work. I did however figure out that the problem was the VPN I'm using. Made an exception for BSManager and it worked flawlessly.
-------- Original Message --------

**Comment by Zagrios** [comment]
Great to know you solved the issue with the VPN! If you need more help, feel free to ask.
