### ISSUE TITLE
[BUG] : Not allowed password when using Steam Guard 

### ISSUE THREAD

**Issue by Raphytator** [Zagrios/bs-manager#241]
I want to download older versions of Beat Saber because since the new versions, mods doesn't work.

To download by BS Manager, i need to enter my ID and Password, but i use Steam Guard to keep safe my account, and BS Manager think the password is wrong when i enter it (i confirm i entered the right password)

I will use the classical download method with import into BS Manager, but that will be great if we can download by BS Manager using Steam Guard on our account.

Thank you

**Comment by Zagrios** [comment]
Hi, BSM fully supports Steam Guard (I use Steam Guard myself).

See : [The Download process with Steam Guard](https://www.youtube.com/watch?v=kJ6_YEYdcQ8)

Each time the "Invalid Password" issue has been reported to us, it turned out to be an issue on the user's side. So, make sure that:
- You use your Steam username, not your display name.
- Your password does not exceed 64 characters. If it does, try to enter only the first 64 characters of your password. (Steam only take the first 64 characters without warn the user if the password exceeds 64 characters)
- You can log into the Steam website with the exact same information you provided to BSM.

**Comment by Raphytator** [comment]
I can log into the Steam website with the exact same information i provied to BSM but i can't into BSM.
My account name is an old format using spaces.

**Comment by Zagrios** [comment]
Oh okay i see, this will be fixed in the next release.

Thanks to have reported us this problem 👌
