### ISSUE TITLE
[FEAT.] : Link with steam

### ISSUE THREAD

**Issue by DrVodka9987** [Zagrios/bs-manager#277]
**Is your feature request related to a problem? Please describe.**
your app says my steam login is wrong when it's the same login i have been using for the past 2 years
**Describe the solution you'd like**
just add a way to link steam to the app, many other have been able to do this 
**Describe alternatives you've considered**

**Additional context**

**Comment by Snailedlt** [comment]
This is very much needed!

Here's a how-to for you developers :)

> Steam OpenID Provider
Steam can act as an OpenID provider. This allows your application to authenticate a user's SteamID without requiring them to enter their Steam username or password on your site (which would be a violation of the API Terms of Use.) Just download an [OpenID library](https://steamcommunity.com/linkfilter/?url=http://openid.net/developers/libraries/) for your language and platform of choice and use https://steamcommunity.com/openid as the provider. The returned Claimed ID will contain the user's 64-bit SteamID. The Claimed ID format is: https://steamcommunity.com/openid/id/<steamid>

source: https://steamcommunity.com/dev

**Comment by Iluhadesu** [comment]
> This is very much needed!
> 
> Here's a how-to for you developers :)
> 
> > Steam OpenID Provider
> > Steam can act as an OpenID provider. This allows your application to authenticate a user's SteamID without requiring them to enter their Steam username or password on your site (which would be a violation of the API Terms of Use.) Just download an [OpenID library](https://steamcommunity.com/linkfilter/?url=http://openid.net/developers/libraries/) for your language and platform of choice and use https://steamcommunity.com/openid as the provider. The returned Claimed ID will contain the user's 64-bit SteamID. The Claimed ID format is: https://steamcommunity.com/openid/id/
> 
> source: https://steamcommunity.com/dev

You can't download a game using OAuth or OpenID authentification and i also already looked into it. Imagine that any website using OAuth will be able to download games ? No you need a real user token to be able to request the keys to decypher the manifests and stuff from Steam to be able to download the game properly and of course Steam doesn't give that with a simple OpenID/OAuth authentification, that's security. Otherwise all website that you authentificated yourself on with Steam, will be able to download all your games. Also we are using [DepotDownloader](https://github.com/SteamRE/DepotDownloader) which uses [SteamKit2](https://github.com/SteamRE/SteamKit) from SteamRE, so there is no other solution, you need a real authentification.


However, we will add the possibility to authentificate yourself using the QRCode method, in a few weeks.


Meanwhile, there is some steps to check why your credentials aren't working (According to previous issues) :
- You use your Steam username, not your display name.
- Your password does not exceed 64 characters. If it does, try to enter only the first 64 characters of your password. (Steam only take the first 64 characters without warn the user if the password exceeds 64 characters)
- You can log into the Steam website with the exact same information you provided to BSM.

**Comment by Snailedlt** [comment]
Makes sense. I thought OpenID could be parameterized to give different permissions, but if it can't it make sense that you can't download games using it.

Happy to hear you'll bring QR login at least :)
That will make it much more convenient!

**Comment by Zagrios** [comment]
Close beacause QRCode has been added
