### ISSUE TITLE
[BUG] : Virtual Desktop Streamer

### ISSUE THREAD

**Issue by Jinxy6677** [Zagrios/bs-manager#322]
I'm new to github so please excuse any blunders. I use virtual desktop streamer to stream from my pc to my oculus but I'm having trouble with using bsmanager with it.

Basically the controls don't work properly. I can't click the thumb sticks in to bring up the in game menu to restart etc. The boxes also aren't being hit when I slice them much more often than when I play beatsaber just through steam + Virtual desktop manager without BS manager.

I can't find anything about compatibility of setting adjustments to make it work properly so I would appreciate any advice :)

**Comment by Zagrios** [comment]
Hi, I don't believe that BSManager is the issue here because BSM simply launches BS and does nothing more. For better support, I recommend you join our Discord and create a post in the #support channel 😉
https://discord.gg/uSqbHVpKdV

If I remember, I will post the solution here for others who might encounter the same issue.

**Comment by Zagrios** [comment]
Closed due to inactivity.
Don't hesitate to reopen if needed
