### ISSUE TITLE
[BUG] :  Only uses oculus even when I have steamvr running

### ISSUE THREAD

**Issue by TimyIsCool** [Zagrios/bs-manager#386]
## Bug Description
I want to play beat saber through steamvr due to streaming/recording etc but it goes through the oculus bypassing steamvr

## Reproduction Steps
Run the game through streamvr or the luancher

## Expected Behavior
Should run through Steamvr

## Screenshots
![image](https://github.com/Zagrios/bs-manager/assets/74112751/cec262cf-0295-4b81-b2ad-e0f186016905)

## System Specs
RTX 3060 
Intel i7-12700f

**Comment by Iluhadesu** [comment]
Hello, Change you default OpenXR runtime to steam, this will work for all version 1.29.4 and above.
![image](https://github.com/Zagrios/bs-manager/assets/92525749/d5e0aa06-a1ea-4495-9326-fbfaaf0cd5c8)

**Comment by TimyIsCool** [comment]
when I do that is seems that Oculus link just will not start

**Comment by Iluhadesu** [comment]
Start Oculus Link first, then SteamVR, then launch the game. If that doesn't work, you should ask on BSMG because this is not a BSManager related issue, and you will have a better answer on what's going on.
[Beat Saber Modding Group's discord (https://discord.gg/beatsabermods)](https://discord.gg/beatsabermods)
