### ISSUE TITLE
[BUG] : Cannot install new versions

### ISSUE THREAD

**Issue by Insprill** [Zagrios/bs-manager#510]
## Bug Description
When trying to install a new version, after selecting the platform (in my case, Steam), the popup closes and it silently fails with the following error:
```
15:18:15.719 › initVersionMetadata error Error: ENOENT: no such file or directory, open '/home/insprill/Documents/BSManager/BSInstances/1.37.0/metadata.config'
```
`1.37.0` is the version I was trying to install. As such, there's no instance folder for it.

## Reproduction Steps
1. Try to install a new version via Steam.

## System Specs
OS: Arch Linux
Version: ca722b2a1835685c0d69187a3ba3e266d1359464

**Comment by Zagrios** [comment]
@Insprill I was able to reproduce once, then nothing, do you still have the issue ?

**Comment by Insprill** [comment]
Yes, the issue is still present for me. I haven't tested on Windows, only on Linux.

**Comment by Zagrios** [comment]
From what i see its a permission issue trying to execute the `DepotDownloader` file on linux 🤔
I will try to look at that this week 👌

**Comment by silentrald** [comment]
@Zagrios, got this to work by getting the new version of [DepotDownloader 2.6.0](https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.6.0) (linux-x64.zip file). Although the QR code doesn't display on the login modal, checking on why that is.

![image](https://github.com/user-attachments/assets/722ab0c7-f696-46de-b597-5362fe62dd4a)

**Comment by silentrald** [comment]
@Zagrios @Insprill, seems that the `DepotDownloader` file that was uploaded to GitHub was corrupted. GitHub only allows 50 MB file size limit and the file is ~70MB, and when I pulled the repository, I only get ~20MB of the file.

Might either need to compress the file within the repo and extract it after its cloned, or just download the build from the original repo so that this repo would conserve space on the git repo. Although, I've created a custom build of [DepotDownloader](https://github.com/silentrald/DepotDownloader/tree/bs-manager) that has support on showing challenge url rather than the qr code in the terminal.

Already created the [fix](https://github.com/silentrald/bs-manager/tree/fix/issue-510), but might need more time since this needs to be hooked with the custom DepotDownloader. The fix also address the issue I've added above.

> Although the QR code doesn't display on the login modal, checking on why that is.

**Comment by Zagrios** [comment]
@silentrald  It's a pretty easy fix. In fact, I have a build that totally works on my machine with Linux (see image 1).
![Capture d’écran du 2024-08-04 14-37-06](https://github.com/user-attachments/assets/6cb3ad43-3a8b-4b5c-a94a-54fdbae08a84)

However, each time I push the file to the repo, Git modifies the file, and then it doesn't work anymore (see image 2).
![image](https://github.com/user-attachments/assets/8f0b01e7-3b79-49c8-aa36-b9521dc1f303)
Here, I have not change the file but it told me that the file has changed :thinking:

**Comment by silentrald** [comment]
@Zagrios 

> However, each time I push the file to the repo, Git modifies the file, and then it doesn't work anymore (see image 2).
Here, I have not change the file but it told me that the file has changed 🤔

Might have something to do with line endings (LF and CRLF). You might need to run this so that you can push LF line endings.

```
git config --global core.autocrlf false
```

Though not sure if that's it tbh, but hopefully it is.

----

But just updating the DepotDownloader didn't work on my end since I got this where QR code just infinitely loading

![image](https://github.com/user-attachments/assets/8813ba00-2cf7-4a8e-ad27-f810c64c2373)

So not sure if the bug fix I created might be still needed in any case. Tell me if you need me to PR it so you can test it as well.

**Comment by Zagrios** [comment]
@silentrald @Insprill The file was not recognize as binary a binary file that was the issue
Can you confirm that it works now ?

**Comment by silentrald** [comment]
@Zagrios, can confirm on my end

**Comment by Insprill** [comment]
Working on my end as well :)

**Comment by Zagrios** [comment]
Nice 🙌
