### ISSUE TITLE
[BUG] : One Click download opens a white screen and never resolves

### ISSUE THREAD

**Issue by AlexGBaker** [Zagrios/bs-manager#643]
### Issue encountered

Updated to the latest version of the manager after an update today, tried to add more songs to and was greeted with this white modal that refuses to resolve when trying to one click download playlists.

![image](https://github.com/user-attachments/assets/f6ae99c8-f121-4ac7-aaf4-5940521da3fa)

### Expected Behavior

Processes the maps properly and wraps up

### Steps to Reproduce

[Navigate to this or](https://beatsaver.com/playlists/170451) [this playlist](https://beatsaver.com/playlists/165539) but the issue seems to be consistent for all the playlists currently. Individual songs seem to work okay.

### Operating System

Windows 10

### Version

v1.4.11

### Additional Context

Individual songs within a playlist seem to work fine.
Issue persists through computer reboots/re-install of the software.

**Comment by silentrald** [comment]
@AlexGBaker can you attach the logs file as well in the post to have more context? Follow this as well to get it
![image](https://github.com/user-attachments/assets/5cd8f9db-2945-4b0f-9b5c-d70ce0e9c7a3)

**Comment by AlexGBaker** [comment]
[2024-11-4-v1.4.11.log](https://github.com/user-attachments/files/17626478/2024-11-4-v1.4.11.log)
Here is the most recent log from my attempt a minute ago.

**Comment by silentrald** [comment]
Yeah seems that this was a bug due to #636, where it changed the ? to %3F. Might need to patch that.

Workaround for that is just downloading the playlist from BSM or if you have the bplist downloaded, we have a drag and drop feature in the latest artifact on alpha. You can download that from here for your testing purposes.

https://github.com/Zagrios/bs-manager/actions/runs/11671066829 (click on release-windows-latest)

**Comment by Medzon888** [comment]
Got same error. Yesterday all was be fine btw

**Comment by AlexGBaker** [comment]
With the update in place this has now been fixed.
